# Generated by Django 3.1.5 on 2021-02-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dateUpdated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
