# Generated by Django 3.1.5 on 2021-02-16 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_auto_20210214_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.fields.NOT_PROVIDED, to='auth.user'),
            preserve_default=False,
        ),
    ]
