# Generated by Django 3.1.5 on 2021-02-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('IT', 'IT'), ('Finance', 'Finance'), ('Dev', 'Dev'), ('Customer Support', 'Customer Support')], max_length=250, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
