# Generated by Django 3.1.5 on 2021-02-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emps', '0002_auto_20210212_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
