# Generated by Django 3.1.5 on 2021-03-01 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risk',
            old_name='rrp',
            new_name='riskResponsePlan',
        ),
    ]
