# Generated by Django 3.1.5 on 2021-02-22 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('projects', '0012_auto_20210219_0753'),
        ('tasks', '0004_auto_20210219_0733'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('classified', models.BooleanField(default=False)),
                ('document', models.FileField(upload_to='')),
                ('kind', models.CharField(blank=True, choices=[('General', 'General'), ('Audit', 'Audit'), ('Memorandum of Association', 'Memorandum of Association'), ('Articles of Association', 'Articles of Association'), ('Prospectus', 'Prospectus'), ('Financial Documents', 'Financial Documents'), ('Minutes', 'Minutes'), ('Business Reports', 'Business Reports')], max_length=30, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateDeleted', models.DateTimeField(blank=True, null=True)),
                ('ReportID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.report')),
                ('creator', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to=settings.AUTH_USER_MODEL)),
                ('projectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('taskID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
            ],
        ),
    ]
