# Generated by Django 3.1.5 on 2021-02-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='dateUpdated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
