# Generated by Django 3.1.5 on 2021-02-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_doc_dateupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='kind',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Audit', 'Audit'), ('Project Related', 'Project Related'), ('Memorandum of Association', 'Memorandum of Association'), ('Articles of Association', 'Articles of Association'), ('Prospectus', 'Prospectus'), ('Financial Documents', 'Financial Documents'), ('Minutes', 'Minutes'), ('Business Reports', 'Business Reports')], max_length=30, null=True),
        ),
    ]
