# Generated by Django 3.1.5 on 2021-02-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20210223_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='ReportID',
            new_name='reportID',
        ),
    ]
