# Generated by Django 3.1.5 on 2021-02-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20210225_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
