# Generated by Django 3.1.5 on 2021-02-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_auto_20210225_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='description',
        ),
    ]
