# Generated by Django 3.1.5 on 2021-02-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_remove_doc_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='kind',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Audit', 'Audit'), ('Project Related', 'Project Related'), ('Policy', 'Policy'), ('Procedures', 'Procedures '), ('Guidelines', 'Guidelines'), ('Forms and templates', 'Forms and templates'), ('Minutes', 'Minutes')], max_length=30, null=True),
        ),
    ]
