# Generated by Django 3.1.5 on 2021-02-14 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='manager',
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ManyToManyField(related_name='tTeam', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ET',
        ),
    ]
