# Generated by Django 3.1.5 on 2021-02-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='productID',
        ),
        migrations.AddField(
            model_name='customer',
            name='dateFinished',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='dateUpdated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='problem',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.CharField(blank=True, choices=[('Blog', 'Blog'), ('Social media', 'Social media'), ('Friend', 'Friend'), ('Google search', 'Google search'), ('Product package', 'Product package'), ('Company Employee', 'Company Employee')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('Unopened', 'Unopened'), ('Inprogress', 'Inprogress'), ('Closed', 'Closed')], max_length=250, null=True),
        ),
    ]
