# Generated by Django 3.1.5 on 2021-02-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custs', '0002_auto_20210228_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('Unopened', 'Unopened'), ('In progress', 'In progress'), ('Closed', 'Closed')], max_length=250, null=True),
        ),
    ]
