# Generated by Django 3.1.5 on 2021-02-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custs', '0003_auto_20210228_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('In progress', 'In progress'), ('Closed', 'Closed')], max_length=250, null=True),
        ),
    ]
